name: Code Quality Analysis

on:
  push:
    branches:
      - main
jobs:
  code-quality-analysis:
    runs-on: ubuntu-latest
    permissions:
     security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Code Analysis with pylint
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
